#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
setopt extended_glob

# Set variables
ZSH_HOME=${ZDOTDIR:-$HOME/.config/zsh}
ZSH_CUSTOM=${ZSH_HOME}/plugins

# Source zstyles you might use with antidote.
[[ -e $ZSH_HOME/zstyles ]] && source $ZSH_HOME/zstyles

# Load local config if it exists.
[[ -e $ZSH_HOME/lib/local.zsh ]] && source $ZSH_HOME/lib/local.zsh

# Create an amazing Zsh config using antidote plugins.
source $ZSH_HOME/lib/antidote.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
