#!/bin/zsh
#
# .zstyles - zstyle settings for features/plugins that need them
#

# Auto convert .... to ../..
zstyle ':zim:input' double-dot-expand no

# Terminal title
zstyle ':zim:termtitle' format '%1~'

# Editor
zstyle ':plugin:editor' emacs 'yes'

# Zimfw git module
# zstyle ':zim:git' aliases-prefix 'g'

# Oh My Zsh config
zstyle ':omz:plugins:docker' aliases no
zstyle ':omz:plugins:docker-compose' aliases no
