#!/usr/bin/env bash

set -euo pipefail

REPO="https://github.com/javalce/dotfiles.git"

# Backup some files
backup_file() {
    if [ -f "$1" ]; then
        cp "$1" "$1.bak"
    fi
}
backup_file "$HOME/.bashrc"
backup_file "$HOME/.profile"
backup_file "$HOME/.zshrc"

# Clone the repository
yadm clone --no-bootstrap "$REPO"

# Checkout the repository
yadm checkout "$HOME"

# Bootstrap the repository
yadm bootstrap
