config:
  backup: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_bin:
    src: bin
    dst: ~/bin
profiles:
  javalce:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - d_kitty
    - d_nvim
    - d_ranger
    - d_bin
