# --- Base Colors ---
background            #06080f
foreground            #f3f6f9
# cursor                #e0c15a
cursor                #ffffff
selection_background  #263356
selection_foreground  #f3f6f9
url_color             #7fb4ca

# --- Tabs ---
active_tab_background   #263356
active_tab_foreground   #f3f6f9
inactive_tab_background #06080f
inactive_tab_foreground #8a8fa3

# --- Normal Colors ---
color0  #06080f
color1  #cb7c94
color2  #b7cc85
color3  #ffe066
color4  #7fb4ca
color5  #ff8dd7
color6  #7aa89f
color7  #f3f6f9

# --- Bright Colors ---
color8  #8a8fa3
color9  #de8fa8
color10 #d1e8a9
color11 #fff7b1
color12 #a3d4d5
color13 #ffaeea
color14 #7fb4ca
color15 #f3f6f9
