[colors]
ansi = [
  "#000000",
  "#c01c28",
  "#26a269",
  "#a2734c",
  "#12488b",
  "#a347ba",
  "#2aa1b3",
  "#d0cfcc",
]
brights = [
  "#5e5c64",
  "#f66151",
  "#33da7a",
  "#e9ad0c",
  "#2a7bde",
  "#c061cb",
  "#33c7de",
  "#ffffff",
]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#ffffff"
cursor_fg = "#111111"
cursor_border = "#ffffff"
selection_bg = "#ffffff"
selection_fg = "#000000"

[colors.indexed]

[metadata]
name = 'GNOME'
